


var joueur = "";

var ncartes = 0; // nombre de cartes

var cartes = [
	{couleur:3, valeur:13},
	{couleur:3, valeur:12},
	{couleur:3, valeur:11},
	{couleur:3, valeur:10},
	{couleur:3, valeur:9},
	{couleur:3, valeur:8},
	{couleur:3, valeur:7},
	{couleur:3, valeur:6},
	{couleur:3, valeur:5},
	{couleur:3, valeur:4},
	{couleur:3, valeur:3},
	{couleur:3, valeur:2},
	{couleur:3, valeur:1},
	{couleur:2, valeur:13},
	{couleur:2, valeur:12},
	{couleur:2, valeur:11},
	{couleur:2, valeur:10},
	{couleur:2, valeur:9},
	{couleur:2, valeur:8},
	{couleur:2, valeur:7},
	{couleur:2, valeur:6},
	{couleur:2, valeur:5},
	{couleur:2, valeur:4},
	{couleur:2, valeur:3},
	{couleur:2, valeur:2},
	{couleur:2, valeur:1},
	{couleur:1, valeur:13},
	{couleur:1, valeur:12},
	{couleur:1, valeur:11},
	{couleur:1, valeur:10},
	{couleur:1, valeur:9},
	{couleur:1, valeur:8},
	{couleur:1, valeur:7},
	{couleur:1, valeur:6},
	{couleur:1, valeur:5},
	{couleur:1, valeur:4},
	{couleur:1, valeur:3},
	{couleur:1, valeur:2},
	{couleur:1, valeur:1},
	{couleur:0, valeur:13},
	{couleur:0, valeur:12},
	{couleur:0, valeur:11},
	{couleur:0, valeur:10},
	{couleur:0, valeur:9},
	{couleur:0, valeur:8},
	{couleur:0, valeur:7},
	{couleur:0, valeur:6},
	{couleur:0, valeur:5},
	{couleur:0, valeur:4},
	{couleur:0, valeur:3},
	{couleur:0, valeur:2},
	{couleur:0, valeur:1}
];

